-- version: optimistic-locking column so concurrent browser tabs saving turns
-- to the same learner+lesson conversation cannot silently overwrite one
-- another's state.
CREATE TABLE lesson_assistant_conversations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                   NOT NULL,
    lesson_id        BIGINT                   NOT NULL,
    messages         JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    preset           TEXT                     NOT NULL DEFAULT 'regular',
    last_response_id TEXT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version          BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_lesson_assistant_conversations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_assistant_conversations_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT uq_lesson_assistant_conversations_user_lesson UNIQUE (user_id, lesson_id)
);
