CREATE TABLE activity_type
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO activity_type (code, name, display_order)
VALUES ('quiz', 'Quiz', 1);
INSERT INTO activity_type (code, name, display_order)
VALUES ('flashcards', 'Flashcards', 2);

CREATE TABLE activity_progress_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO activity_progress_status (code, name, display_order)
VALUES ('not_started', 'Not Started', 1);
INSERT INTO activity_progress_status (code, name, display_order)
VALUES ('in_progress', 'In Progress', 2);
INSERT INTO activity_progress_status (code, name, display_order)
VALUES ('completed', 'Completed', 3);
INSERT INTO activity_progress_status (code, name, display_order)
VALUES ('failed', 'Failed', 4);

-- version: optimistic-locking column so two lesson managers editing the same
-- activity's question set concurrently cannot silently overwrite one another.
CREATE TABLE lesson_activities
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id    TEXT UNIQUE,
    lesson_id           BIGINT                   NOT NULL,
    type_id             BIGINT                   NOT NULL,
    title               TEXT                     NOT NULL DEFAULT '',
    item_count          INT                      NOT NULL DEFAULT 0,
    payload             JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    generation_metadata JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_by          TEXT                     NOT NULL DEFAULT '',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version             BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_lesson_activities_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_activities_type FOREIGN KEY (type_id) REFERENCES activity_type (id)
);

CREATE INDEX lesson_activities_lesson_id_idx ON lesson_activities (lesson_id, created_at DESC);

-- version: optimistic-locking column so a quiz/flashcard completion and a
-- progress reset racing on the same (user, activity) row cannot silently
-- overwrite one another's score/status.
CREATE TABLE user_lesson_activity_progress
(
    user_id      BIGINT                   NOT NULL,
    activity_id  BIGINT                   NOT NULL,
    lesson_id    BIGINT                   NOT NULL,
    status_id    BIGINT                   NOT NULL,
    score        NUMERIC,
    metadata     JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    started_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version      BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT pk_user_lesson_activity_progress PRIMARY KEY (user_id, activity_id),
    CONSTRAINT fk_ulap_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulap_activity FOREIGN KEY (activity_id) REFERENCES lesson_activities (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulap_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulap_status FOREIGN KEY (status_id) REFERENCES activity_progress_status (id)
);

CREATE INDEX user_lesson_activity_progress_lesson_idx ON user_lesson_activity_progress (user_id, lesson_id);

CREATE TABLE user_lesson_activity_attempts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id  TEXT UNIQUE,
    user_id           BIGINT                   NOT NULL,
    activity_id       BIGINT                   NOT NULL,
    lesson_id         BIGINT                   NOT NULL,
    type_id           BIGINT                   NOT NULL,
    attempt_number    INT                      NOT NULL,
    score             NUMERIC,
    passed            BOOLEAN                  NOT NULL DEFAULT false,
    correct_count     INT                      NOT NULL DEFAULT 0,
    total_count       INT                      NOT NULL DEFAULT 0,
    submitted_answers JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    results           JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    metadata          JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ulaa_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulaa_activity FOREIGN KEY (activity_id) REFERENCES lesson_activities (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulaa_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulaa_type FOREIGN KEY (type_id) REFERENCES activity_type (id),
    CONSTRAINT user_lesson_activity_attempts_number_unique UNIQUE (user_id, activity_id, attempt_number)
);

CREATE INDEX user_lesson_activity_attempts_user_activity_idx ON user_lesson_activity_attempts (user_id, activity_id, created_at DESC);
CREATE INDEX user_lesson_activity_attempts_lesson_idx ON user_lesson_activity_attempts (user_id, lesson_id, created_at DESC);
