CREATE TABLE lesson_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO lesson_status (code, name, display_order)
VALUES ('draft', 'Draft', 1);
INSERT INTO lesson_status (code, name, display_order)
VALUES ('generating', 'Generating', 2);
INSERT INTO lesson_status (code, name, display_order)
VALUES ('ready', 'Ready', 3);
INSERT INTO lesson_status (code, name, display_order)
VALUES ('failed', 'Failed', 4);

CREATE TABLE lesson_publication_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO lesson_publication_status (code, name, display_order)
VALUES ('published', 'Published', 1);
INSERT INTO lesson_publication_status (code, name, display_order)
VALUES ('private', 'Private', 2);
INSERT INTO lesson_publication_status (code, name, display_order)
VALUES ('archived', 'Archived', 3);

CREATE TABLE lesson_content_format
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO lesson_content_format (code, name, display_order)
VALUES ('markdown', 'Markdown', 1);

-- Includes the 'video' kind (originally added by a follow-up changeset once
-- video lesson assets shipped) directly in the initial seed set.
CREATE TABLE lesson_asset_kind
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO lesson_asset_kind (code, name, display_order)
VALUES ('link', 'Link', 1);
INSERT INTO lesson_asset_kind (code, name, display_order)
VALUES ('youtube', 'YouTube', 2);
INSERT INTO lesson_asset_kind (code, name, display_order)
VALUES ('image', 'Image', 3);
INSERT INTO lesson_asset_kind (code, name, display_order)
VALUES ('file', 'File', 4);
INSERT INTO lesson_asset_kind (code, name, display_order)
VALUES ('video', 'Video', 5);

-- version: optimistic-locking column so concurrent write paths onto the same
-- lesson (manual edit, AI revision, asset-delete cleanup, teacher-video generation)
-- cannot silently overwrite one another.
CREATE TABLE lessons
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id          TEXT UNIQUE,
    title                     TEXT                     NOT NULL,
    description               TEXT                     NOT NULL DEFAULT '',
    status_id                 BIGINT                   NOT NULL,
    user_instructions         TEXT                     NOT NULL DEFAULT '',
    depth                     TEXT                     NOT NULL DEFAULT 'standard',
    tone                      TEXT                     NOT NULL DEFAULT 'clear',
    desired_format            TEXT                     NOT NULL DEFAULT 'structured theoretical lesson',
    content_format_id         BIGINT                   NOT NULL,
    content_markdown          TEXT                     NOT NULL DEFAULT '',
    content_html              TEXT                     NOT NULL DEFAULT '',
    cover_image_storage_key   TEXT                     NOT NULL DEFAULT '',
    cover_image_original_name TEXT                     NOT NULL DEFAULT '',
    cover_image_mime_type     TEXT                     NOT NULL DEFAULT '',
    generation_metadata       JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    revision_history          JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    error_message             TEXT                     NOT NULL DEFAULT '',
    publication_status_id     BIGINT                   NOT NULL,
    published_at              TIMESTAMP WITH TIME ZONE,
    created_by_user_id        BIGINT,
    created_by                TEXT                     NOT NULL DEFAULT '',
    tags                      JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                   BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_lessons_status FOREIGN KEY (status_id) REFERENCES lesson_status (id),
    CONSTRAINT fk_lessons_content_format FOREIGN KEY (content_format_id) REFERENCES lesson_content_format (id),
    CONSTRAINT fk_lessons_publication_status FOREIGN KEY (publication_status_id) REFERENCES lesson_publication_status (id),
    CONSTRAINT fk_lessons_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX lessons_created_at_idx ON lessons (created_at DESC);
CREATE INDEX lessons_status_publication_created_at_idx ON lessons (status_id, publication_status_id, created_at DESC);
CREATE INDEX lessons_publication_status_created_at_idx ON lessons (publication_status_id, created_at DESC);
CREATE INDEX lessons_created_by_user_id_created_at_idx ON lessons (created_by_user_id, created_at DESC);
CREATE INDEX lessons_tags_gin_idx ON lessons USING gin (tags);

CREATE TABLE lesson_materials
(
    lesson_id   BIGINT                   NOT NULL,
    material_id BIGINT                   NOT NULL,
    sort_order  INT                      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lesson_materials PRIMARY KEY (lesson_id, material_id),
    CONSTRAINT fk_lesson_materials_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_materials_material FOREIGN KEY (material_id) REFERENCES materials (id) ON DELETE RESTRICT
);

CREATE INDEX lesson_materials_material_id_idx ON lesson_materials (material_id);

CREATE TABLE lesson_assets
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id TEXT UNIQUE,
    lesson_id        BIGINT                   NOT NULL,
    kind_id          BIGINT                   NOT NULL,
    title            TEXT                     NOT NULL DEFAULT '',
    url              TEXT                     NOT NULL DEFAULT '',
    description      TEXT                     NOT NULL DEFAULT '',
    image_url        TEXT                     NOT NULL DEFAULT '',
    site_name        TEXT                     NOT NULL DEFAULT '',
    original_name    TEXT                     NOT NULL DEFAULT '',
    storage_key      TEXT                     NOT NULL DEFAULT '',
    mime_type        TEXT                     NOT NULL DEFAULT '',
    size_bytes       BIGINT                   NOT NULL DEFAULT 0,
    metadata         JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lesson_assets_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_assets_kind FOREIGN KEY (kind_id) REFERENCES lesson_asset_kind (id)
);

CREATE INDEX lesson_assets_lesson_id_idx ON lesson_assets (lesson_id, created_at);
