CREATE TABLE material_file_kind
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    display_order INT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO material_file_kind (code, name, display_order)
VALUES ('file', 'File', 1);
INSERT INTO material_file_kind (code, name, display_order)
VALUES ('image', 'Image', 2);

-- version: optimistic-locking column so two admins editing the same shared
-- material (referenced by multiple lessons) concurrently cannot silently overwrite one another.
CREATE TABLE materials
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id          TEXT UNIQUE,
    title                     TEXT                     NOT NULL,
    description               TEXT                     NOT NULL DEFAULT '',
    text_content              TEXT                     NOT NULL DEFAULT '',
    tags                      JSONB                    NOT NULL DEFAULT '[]'::jsonb,
    created_by_user_id        BIGINT,
    created_by                TEXT                     NOT NULL DEFAULT '',
    cover_image_storage_key   TEXT                     NOT NULL DEFAULT '',
    cover_image_original_name TEXT                     NOT NULL DEFAULT '',
    cover_image_mime_type     TEXT                     NOT NULL DEFAULT '',
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                   BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_materials_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX materials_created_at_idx ON materials (created_at DESC);
CREATE INDEX materials_created_by_user_id_idx ON materials (created_by_user_id);
CREATE INDEX materials_tags_gin_idx ON materials USING gin (tags);

CREATE TABLE material_files
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id    TEXT UNIQUE,
    material_id         BIGINT                   NOT NULL,
    kind_id             BIGINT                   NOT NULL,
    original_name       TEXT                     NOT NULL,
    storage_key         TEXT                     NOT NULL,
    mime_type           TEXT                     NOT NULL DEFAULT '',
    size_bytes          BIGINT                   NOT NULL DEFAULT 0,
    openai_file_id      TEXT,
    openai_file_purpose TEXT                     NOT NULL DEFAULT '',
    openai_file_status  TEXT                     NOT NULL DEFAULT '',
    openai_file_error   TEXT                     NOT NULL DEFAULT '',
    openai_uploaded_at  TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_material_files_material FOREIGN KEY (material_id) REFERENCES materials (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_files_kind FOREIGN KEY (kind_id) REFERENCES material_file_kind (id)
);

CREATE INDEX material_files_material_id_idx ON material_files (material_id);
CREATE INDEX material_files_storage_key_idx ON material_files (storage_key);

CREATE TABLE material_youtube_urls
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id TEXT UNIQUE,
    material_id      BIGINT NOT NULL,
    url              TEXT   NOT NULL,
    sort_order       INT    NOT NULL,
    title            TEXT   NOT NULL DEFAULT '',
    author_name      TEXT   NOT NULL DEFAULT '',
    author_url       TEXT   NOT NULL DEFAULT '',
    thumbnail_url    TEXT   NOT NULL DEFAULT '',
    thumbnail_width  INT,
    thumbnail_height INT,
    provider_name    TEXT   NOT NULL DEFAULT '',
    metadata_error   TEXT   NOT NULL DEFAULT '',
    CONSTRAINT fk_material_youtube_material FOREIGN KEY (material_id) REFERENCES materials (id) ON DELETE CASCADE
);

CREATE INDEX material_youtube_urls_material_id_sort_order_idx ON material_youtube_urls (material_id, sort_order);

CREATE TABLE material_links
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id TEXT UNIQUE,
    material_id      BIGINT NOT NULL,
    url              TEXT   NOT NULL,
    sort_order       INT    NOT NULL,
    title            TEXT   NOT NULL DEFAULT '',
    description      TEXT   NOT NULL DEFAULT '',
    image_url        TEXT   NOT NULL DEFAULT '',
    site_name        TEXT   NOT NULL DEFAULT '',
    extracted_text   TEXT   NOT NULL DEFAULT '',
    metadata_error   TEXT   NOT NULL DEFAULT '',
    CONSTRAINT fk_material_links_material FOREIGN KEY (material_id) REFERENCES materials (id) ON DELETE CASCADE
);

CREATE INDEX material_links_material_id_sort_order_idx ON material_links (material_id, sort_order);
