CREATE TABLE pending_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key TEXT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    expected_content_type TEXT NOT NULL,
    expected_size_bytes BIGINT NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_pending_uploads_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_pending_uploads_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_pending_uploads_cleanup_sweep ON pending_uploads (confirmed, expires_at);
