CREATE TABLE roadmap_team_assignments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id          BIGINT                   NOT NULL,
    lead_user_id        BIGINT                   NOT NULL,
    assigned_by_user_id BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_roadmap_team_assignments_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_team_assignments_lead FOREIGN KEY (lead_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_team_assignments_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uq_roadmap_team_assignments_roadmap_lead UNIQUE (roadmap_id, lead_user_id)
);

CREATE INDEX roadmap_team_assignments_lead_user_id_idx ON roadmap_team_assignments (lead_user_id);
