CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO user_role (code, name, display_order) VALUES ('admin', 'Admin', 1);
INSERT INTO user_role (code, name, display_order) VALUES ('teamlead', 'Team Lead', 2);
INSERT INTO user_role (code, name, display_order) VALUES ('member', 'Member', 3);

-- version: optimistic-locking column so concurrent edits to a user's role,
-- grade, or profile fields (name/position/avatar) cannot silently overwrite one another.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id TEXT UNIQUE,
    clerk_user_id TEXT UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role_id BIGINT NOT NULL,
    position TEXT,
    avatar_storage_key TEXT,
    avatar_color TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES user_role (id)
);
