-- Explicit groups + configurable grades, additive to the legacy lead-based
-- team model (team_members, roadmap_team_assignments). Legacy tables and the
-- code paths built on them stay live and are not superseded by this model.

CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    display_order INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_grades_code UNIQUE (code)
);

INSERT INTO grades (code, name, display_order, is_active) VALUES ('junior', 'Junior', 1, true);
INSERT INTO grades (code, name, display_order, is_active) VALUES ('middle', 'Middle', 2, true);
INSERT INTO grades (code, name, display_order, is_active) VALUES ('senior', 'Senior', 3, true);

ALTER TABLE users ADD COLUMN grade_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_grade FOREIGN KEY (grade_id) REFERENCES grades (id) ON DELETE SET NULL;
CREATE INDEX users_grade_id_idx ON users (grade_id);

-- version: optimistic-locking column so two leads editing the same group's
-- name/description concurrently cannot silently overwrite one another.
CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_groups_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX ux_groups_normalized_name ON groups (normalized_name);

CREATE TABLE group_leads (
    group_id BIGINT NOT NULL,
    lead_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_group_leads PRIMARY KEY (group_id, lead_user_id),
    CONSTRAINT fk_group_leads_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_leads_lead FOREIGN KEY (lead_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX group_leads_lead_user_id_idx ON group_leads (lead_user_id);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    member_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_group_members PRIMARY KEY (group_id, member_user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_member FOREIGN KEY (member_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX group_members_member_user_id_idx ON group_members (member_user_id);

-- version: optimistic-locking column so two admins concurrently editing the
-- same roadmap-to-group assignment cannot silently overwrite one another.
-- Since assignRoadmapToGroup always saves this row before replacing its
-- grade-filter child rows, this single version check also guards the
-- child-row replace.
CREATE TABLE roadmap_group_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_roadmap_group_assignments_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_group_assignments_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_group_assignments_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uq_roadmap_group_assignments_roadmap_group UNIQUE (roadmap_id, group_id)
);

CREATE INDEX roadmap_group_assignments_group_id_idx ON roadmap_group_assignments (group_id);

CREATE TABLE roadmap_group_assignment_grades (
    assignment_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    CONSTRAINT pk_roadmap_group_assignment_grades PRIMARY KEY (assignment_id, grade_id),
    CONSTRAINT fk_rgag_assignment FOREIGN KEY (assignment_id) REFERENCES roadmap_group_assignments (id) ON DELETE CASCADE,
    CONSTRAINT fk_rgag_grade FOREIGN KEY (grade_id) REFERENCES grades (id) ON DELETE CASCADE
);
