-- version: optimistic-locking column so concurrent edits to the same roadmap
-- (title/description/tags/lesson-list) cannot silently overwrite one another.
CREATE TABLE roadmaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source_id TEXT UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    author_user_id BIGINT,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_roadmaps_author FOREIGN KEY (author_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX roadmaps_created_at_idx ON roadmaps (created_at DESC);
CREATE INDEX roadmaps_author_user_id_created_at_idx ON roadmaps (author_user_id, created_at DESC);
CREATE INDEX roadmaps_tags_gin_idx ON roadmaps USING gin (tags);

CREATE TABLE roadmap_lessons (
    roadmap_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_roadmap_lessons PRIMARY KEY (roadmap_id, lesson_id),
    CONSTRAINT fk_roadmap_lessons_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_lessons_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE INDEX roadmap_lessons_lesson_id_idx ON roadmap_lessons (lesson_id);

CREATE TABLE user_roadmaps (
    user_id BIGINT NOT NULL,
    roadmap_id BIGINT NOT NULL,
    enrolled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_roadmaps PRIMARY KEY (user_id, roadmap_id),
    CONSTRAINT fk_user_roadmaps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roadmaps_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id) ON DELETE CASCADE
);

CREATE INDEX user_roadmaps_roadmap_id_idx ON user_roadmaps (roadmap_id);
