-- Aligned with the AI Digital BigQuery usage-logging schema. Required cols:
-- event_id, event_timestamp, service, event_type. Everything else nullable
-- so a partial / fire-and-forget event still lands. correlation_id is NOT
-- a top-level column here (BQ guide doesn't have one) -- the aspect writes
-- it inside `attributes` JSON instead.

CREATE TABLE usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    service TEXT NOT NULL,
    environment TEXT,
    event_type TEXT NOT NULL,
    action TEXT,
    user_id TEXT,
    user_email TEXT,
    status TEXT,
    duration_ms BIGINT,
    attributes JSONB,
    error_message TEXT,
    client_ip TEXT,
    user_agent TEXT
);

CREATE INDEX idx_usage_events_service_ts ON usage_events (service, event_timestamp DESC);
CREATE INDEX idx_usage_events_action_ts ON usage_events (action, event_timestamp DESC);
