// @ConfigurationProperties bean — typed home for Clerk SSO settings.
// Maps from application.yml `app.auth.*` and the AUTH_* / CLERK_* env vars.

package com.aidigital.aionboarding.security;

import jakarta.validation.constraints.NotNull;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.validation.annotation.Validated;

/**
 * Typed configuration for Clerk SSO authentication.
 *
 * <p>Accessors are written out rather than generated by Lombok. This is the one
 * backend class where that is required: the CI gate rejects Lombok accessor
 * annotations here (see docs/aiae-template-change-requests.md, CR-18).
 * Everywhere else the project rule stands — use Lombok instead of handwritten
 * boilerplate. Do not name those annotations in this file even inside a
 * comment: the gate greps the raw text and cannot tell code from prose.
 *
 * <p>Spring binds these properties through the JavaBean accessors below, so the
 * setters are called by the framework even where no source call site exists.
 */
@Validated
@ConfigurationProperties(prefix = "app.auth")
public class AuthProperties {

    /** Company email domain without a leading {@code @}. */
    private String allowedEmailDomain = "aidigital.com";

    /** Clerk publishable key — derives issuer/JWKS when explicit URIs are blank. */
    private String publishableKey;

    /**
     * Comma-separated list of exact trusted browser origins for the JWT
     * {@code azp} (authorized party) claim, e.g.
     * {@code http://localhost:5173,https://my-app.replit.app}. Never a Clerk
     * publishable key. Blank fails startup via {@link AuthStartupValidator}.
     */
    private String authorizedParties = "";

    @NotNull
    private Sso sso = new Sso();

    /**
     * Returns the company email domain that authenticated users must belong to.
     *
     * @return the domain without a leading {@code @}, never {@code null} unless
     *         explicitly configured as such
     */
    public String getAllowedEmailDomain() {
        return allowedEmailDomain;
    }

    /**
     * Sets the company email domain that authenticated users must belong to.
     *
     * @param allowedEmailDomain the domain without a leading {@code @}
     */
    public void setAllowedEmailDomain(String allowedEmailDomain) {
        this.allowedEmailDomain = allowedEmailDomain;
    }

    /**
     * Returns the Clerk publishable key used to derive the issuer and JWKS URIs
     * when those are not configured explicitly.
     *
     * @return the publishable key, or {@code null} when the explicit URIs are used
     */
    public String getPublishableKey() {
        return publishableKey;
    }

    /**
     * Sets the Clerk publishable key.
     *
     * @param publishableKey the publishable key; never a secret key
     */
    public void setPublishableKey(String publishableKey) {
        this.publishableKey = publishableKey;
    }

    /**
     * Returns the trusted browser origins accepted in the JWT {@code azp} claim.
     *
     * @return a comma-separated list of exact origins; blank fails startup
     */
    public String getAuthorizedParties() {
        return authorizedParties;
    }

    /**
     * Sets the trusted browser origins accepted in the JWT {@code azp} claim.
     *
     * @param authorizedParties a comma-separated list of exact origins
     */
    public void setAuthorizedParties(String authorizedParties) {
        this.authorizedParties = authorizedParties;
    }

    /**
     * Returns the SSO/OIDC sub-group.
     *
     * @return the SSO settings, defaulted to an empty group so callers never
     *         dereference {@code null}
     */
    public Sso getSso() {
        return sso;
    }

    /**
     * Sets the SSO/OIDC sub-group. Called by Spring during property binding.
     *
     * @param sso the SSO settings; {@code null} is rejected by {@code @NotNull}
     */
    public void setSso(Sso sso) {
        this.sso = sso;
    }

    /**
     * SSO/OIDC settings for Clerk or another compatible provider.
     */
    public static class Sso {

        /** Clerk issuer URI, e.g. https://clean-clerk.clerk.accounts.dev */
        private String issuerUri;

        /** Optional JWKS override; usually discovered from issuerUri. */
        private String jwkSetUri;

        /** Expected `aud` claim value. */
        private String audience;

        /**
         * Returns the OIDC issuer URI.
         *
         * @return the issuer URI, or {@code null} when derived from the
         *         publishable key instead
         */
        public String getIssuerUri() {
            return issuerUri;
        }

        /**
         * Sets the OIDC issuer URI.
         *
         * @param issuerUri the issuer URI
         */
        public void setIssuerUri(String issuerUri) {
            this.issuerUri = issuerUri;
        }

        /**
         * Returns the JWKS URI override.
         *
         * @return the JWKS URI, or {@code null} to discover it from the issuer
         */
        public String getJwkSetUri() {
            return jwkSetUri;
        }

        /**
         * Sets the JWKS URI override.
         *
         * @param jwkSetUri the JWKS URI
         */
        public void setJwkSetUri(String jwkSetUri) {
            this.jwkSetUri = jwkSetUri;
        }

        /**
         * Returns the expected {@code aud} claim value.
         *
         * @return the audience, or {@code null} when the claim is not checked
         */
        public String getAudience() {
            return audience;
        }

        /**
         * Sets the expected {@code aud} claim value.
         *
         * @param audience the audience
         */
        public void setAudience(String audience) {
            this.audience = audience;
        }
    }
}
